version: '3.4'

services:
  proxy:
    ports:
      - "80:80"
    restart: always

  client:
    ports:
      - "9000:80"
    restart: always

  api:
    env_file:
      - .env
      - secrets.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - DefaultUser__UserName=${DEFAULT_USERNAME}
      - DefaultUser__Password=${DEFAULT_PASSWORD}
      - DefaultUser__Email=${DEFAULT_EMAIL}
      - MailServer__From=${MAILSERVER_FROM}
      - MailServer__SmtpClient=${MAILSERVER_SMTP}
    ports:
      - "5000:5000"
    restart: always

  db:
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - sqldata:/var/lib/mysql
    restart: always

volumes:
  sqldata: