version: '3.4'

services:
  studycontrolsoftware-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000;https://+:5001;
    env_file:
      - .env
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    restart: always

  db:
    environment:
      - MYSQL_ROOT_PASSWORD=root12
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user12
      - MYSQL_DATABASE=study_control_software
    ports:
      - '3306:3306'
    volumes:
      - sqldata:/var/lib/mysql
    restart: always

volumes:
  sqldata: