version: '3.4'

services:
  studycontrolsoftware-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
    ports:
      - "5001:5001"
      - "5000:5000"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    restart: always

  db:
    environment:
       MYSQL_ROOT_PASSWORD: root12
       MYSQL_DATABASE: study_control_software
       MYSQL_USER: user
       MYSQL_PASSWORD: user12
    volumes:
       - sqldata:/var/lib/mysql
    ports:
      - '3306:3306'
    restart: always

volumes:
  sqldata: